#!/usr/bin/zsh
# This function checks current EE data allowance status.
function eedata() {
  local url='http://add-on.ee.co.uk/status'
  local html=$(curl -s $url)
  if [[ -z $html ]]
  then
    echo 'Error: Unable to establish a connection to EE.'
  elif [[ $(echo $html | pup 'title text{}') == 'Error' ]]
  then
    echo 'Error: The default route is not via EE.'
  else
    echo $html | pup 'span.allowance__left text{}' | tr -d '\n' | awk '{$2=$2};1'
    echo $html | pup 'p.allowance__timespan text{}' | tr -d '\n' | awk '{$2=$2};1'
    echo $html | pup 'div.allowance__recurrence-info text{}' | tr -d '\n' | awk '{$2=$2};1'
    echo $html | pup 'div.free-data__content text{}' | tr -d '\n' | awk '{$2=$2};1'
  fi
}
