#!/usr/bin/zsh
# This function checks current EE data allowance status.
function eedata() {
  local url='http://add-on.ee.co.uk/status'
  local html=$(curl -s $url)
  if [[ -z $html ]]
  then
    echo 'Error: Unable to establish a connection to EE.'
  elif [[ $(pup 'title text{}' <<< $html) == 'Error' ]]
  then
    echo 'Error: The default route is not via EE.'
  else
    pup 'span.allowance__left text{}' <<< $html | tr -d '\n' | awk '{$1=$1};1'
    pup 'p.allowance__timespan text{}' <<< $html | tr -d '\n' | awk '{$1=$1};1'
    pup 'div.allowance__recurrence-info text{}' <<< $html | tr -d '\n' | awk '{$1=$1};1'
    pup 'div.free-data__content text{}' <<< $html | tr -d '\n' | awk '{$1=$1};1'
  fi
}
